variables:
- name: repositoryName #Nombre del repositorio de azure DevOps
  value: 'c-breb-modificacionllaves-p2m-ms-dotnet' 
- name: solutionName #Nombre de la solucion
  value: 'SPI-Update-Service.sln'
- name: solutionRoute #Ruta de la solucion
  value: 'src'
- name: dockerfileRoute #Ruta del dockerfile
  value: 'src'
- name: EcrRepositoryName #Nombre del repositorio de ECR
  value: 'breb-modificacionllavesp2m'
- name: UrlGitRepository #Url del repositorio de git
  value: 'bancoserfinanza@dev.azure.com/bancoserfinanza/REDEBAN/_git/c-breb-modificacionllaves-p2m-ms-dotnet'